screen_width = Window.GetWidth();
screen_height = Window.GetHeight();

frame = 0;

images[0]  = Image("splash_frame_00.png");
images[1]  = Image("splash_frame_01.png");
images[2]  = Image("splash_frame_02.png");
images[3]  = Image("splash_frame_03.png");
images[4]  = Image("splash_frame_04.png");
images[5]  = Image("splash_frame_05.png");
images[6]  = Image("splash_frame_06.png");
images[7]  = Image("splash_frame_07.png");
images[8]  = Image("splash_frame_08.png");
images[9]  = Image("splash_frame_09.png");
images[10] = Image("splash_frame_10.png");
images[11] = Image("splash_frame_11.png");

sprite = Sprite(images[0]);

x = (screen_width - 346) / 2;
y = (screen_height - 480) / 2;

sprite.SetPosition(x, y, 0);

fun animate_callback() {
    frame++;
    if (frame >= 12)
        frame = 0;

    sprite.SetImage(images[frame]);
}

Plymouth.SetRefreshFunction(animate_callback);
